name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: setup
      run: ./bin/setup
    - name: tests
      run: ./bin/run-tests
